
project_id = "pozblfzhjqlsxkakhowp"

[api]
port = 54321
schemas = ["public", "storage", "extensions"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
major_version = 15

[studio]
port = 54323

[inbucket]
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
file_size_limit = "50MiB"

[auth]
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://localhost:3000"]
jwt_expiry = 3600
enable_refresh_token_rotation = true
refresh_token_reuse_interval = 10
enable_signup = true

[analytics]
port = 54327
vector_port = 54328

[functions]
# Port to use for Functions API serving.

[functions.verify-payment]
verify_jwt = true

[functions.create-subscription]
verify_jwt = true

[functions.stripe-webhook]
verify_jwt = false

[functions.cancel-subscription]
verify_jwt = true

[functions.create-payment-update-session]
verify_jwt = true

[functions.create-connect-account]
verify_jwt = true

[functions.create-connect-payment]
verify_jwt = true

[functions.submit-waitlist-email]
verify_jwt = false
